run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - gomoddirectives
    - gomodguard
    - ireturn
    - nilnil
    - nlreturn
    - paralleltest
    - testpackage
    - wrapcheck
    - wsl
    - depguard
    - gomnd
    - mnd

linters-settings:
  funlen:
    lines: 80
    statements: 50
  
  gocognit:
    min-complexity: 20
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  
  gofumpt:
    extra-rules: true
  
  goimports:
    local-prefixes: github.com/restayway/stx
  
  golint:
    min-confidence: 0
  
  govet:
    check-shadowing: true
  
  lll:
    line-length: 140
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - gomnd
        - goconst
        - gocyclo
        - funlen
        - lll
        - gocognit